const questions = [

    {
        one: "لاعب فاز بالدوري الاسباني و الالماني و الانجليزي",
        two: "لاعبين دربهم مورينيو",
        three: "لاعبين افارقة غير مصريين",
        four:"فرق شمال افريقية غير مصرية",
        five: "لاعبين لعبوا مع محمد صلاح",
        six: "ملاعب مصرية",
        seven:"فرق تأهلت للدوري الانجليزي الممتاز من ٢٠١٠",
        eight:"فرق في التشامبيون شيب",
        nine:"لاعبين ارتدوا الرقم ١٠ مع منتخباتهم",
        ten:"10",
        eleven:"11",
        twelve:"12",
        thirteen:"13",
        fourteen:"14",
        fifteen:"15",
        sixteen:"16",
        seventeen:"17",
        eighteen:"18",
        nineteen:"19",
        twenty:"20",
        twentyone:"21",
        twentytwo:"22",
        twentythree:"23",
        twentyfour:"24",
        twentyfive:"25",
        twentysix:"26",
        twentyseven:"27",
        twentyeight:"28",
        twentynine:"29",
        thirty:"30",
    },

    {
        one: "100",
        two: "200",
        three: "300",
        four:"400",
        five: "500",
        six: "600",
        seven:"700",
        eight:"800",
        nine:"900",
        ten:"1000",
        eleven:"1100",
        twelve:"1200",
        thirteen:"1300",
        fourteen:"1400",
        fifteen:"1500",
        sixteen:"1600",
        seventeen:"1700",
        eighteen:"1800",
        nineteen:"1900",
        twenty:"2000",
        twentyone:"2100",
        twentytwo:"2200",
        twentythree:"2300",
        twentyfour:"2400",
        twentyfive:"2500",
        twentysix:"2600",
        twentyseven:"2700",
        twentyeight:"2800",
        twentynine:"2900",
        thirty:"3000",
    },

];
  
export default questions;